### ISSUE TITLE
Feature: User can login or sign up to play the game

### ISSUE THREAD

**Issue by yanganboada** [yanganboada/alexspuzzle#1]
## ⚙️ Feature

> ##### Game Main Page
> ##### Login
> ##### Sign up

## 📐 Functionality

> ##### User can choose login on sign up on front page.
> ##### User can sign up with email and password.
> ##### User can login with email and password.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![login sign up](https://user-images.githubusercontent.com/53366955/143663016-3b148144-abed-4a36-8832-110d5d0b40f7.gif)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to `schema.sql`
- [ ] Update `data.sql` to `data.sql`

### ☁️ Server

- [ ] Update `server/index.js` to `server/index.js`
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to `index.jsx`
- [ ] Create a component to `app.jsx`
- [ ] Create a component to `login.jsx`
- [ ] Create a component to `sign-up.jsx`
- [ ] Create a component to `play.jsx`
- [ ] Create a component to `set-up-profile.jsx`

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
