### ISSUE TITLE
Feature: User can add profile

### ISSUE THREAD

**Issue by yanganboada** [yanganboada/alexspuzzle#2]
## ⚙️ Feature

> ##### Image upload
> ##### Form submission

## 📐 Functionality

> ##### User can add/save profile and add avatar

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Save profile](https://user-images.githubusercontent.com/53366955/143984184-3d39e3da-b731-4377-bc50-7db963e4f067.gif)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `data.sql` to `data.sql`

### ☁️ Server

- [ ] Update `server/index.js` to `server/index.js` 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update a component to `sign-up.jsx`
- [ ] Update a component to `set-up-profile.jsx`

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
